MSPR/src/Entity/Comments.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\CommentsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentsRepository::class)]
#[ApiResource]
class Comments
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 500, nullable: true)]
    private ?string $content = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $type = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Post $post = null;

    #[ORM\ManyToOne(inversedBy: 'Comments')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user_comment = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $send_date = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getPost(): ?Post
    {
        return $this->post;
    }

    public function setPost(?Post $post): self
    {
        $this->post = $post;

        return $this;
    }

    public function getUserComment(): ?User
    {
        return $this->user_comment;
    }

    public function setUserComment(?User $user_comment): self
    {
        $this->user_comment = $user_comment;

        return $this;
    }

    public function getSendDate(): ?\DateTimeInterface
    {
        return $this->send_date;
    }

    public function setSendDate(\DateTimeInterface $send_date): self
    {
        $this->send_date = $send_date;

        return $this;
    }
}

MSPR/src/Entity/Post.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\PostRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Ignore;

#[ORM\Entity(repositoryClass: PostRepository::class)]
#[ApiResource]
class Post
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(nullable: true)]
    private ?bool $is_held = null;

    #[ORM\OneToMany(mappedBy: 'post', targetEntity: Comments::class, orphanRemoval: true)]
    private Collection $comments;

    #[ORM\ManyToOne(cascade: ['persist'], inversedBy: 'guarded_posts')]
    #[Ignore]
    private ?User $guardian = null;

    #[ORM\Column(type: "string")]
    private $image = null;

    #[ORM\ManyToOne(inversedBy: 'posts')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Plant $plantId = null;

    #[ORM\ManyToOne(inversedBy: 'post')]
    #[Ignore]
    private ?User $user = null;

    #[ORM\Column(length: 255)]
    private ?string $longitude = null;

    #[ORM\Column(length: 255)]
    private ?string $latitude = null;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function IsHeld(): ?bool
    {
        return $this->is_held;
    }

    public function setIsHeld(?bool $is_held): self
    {
        $this->is_held = $is_held;

        return $this;
    }
    /**
     * @return Collection<int, Comments>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setPost($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getPost() === $this) {
                $comment->setPost(null);
            }
        }

        return $this;
    }

    public function getGuardian(): ?User
    {
        return $this->guardian;
    }

    public function setGuardian(?User $guardian): self
    {
        $this->guardian = $guardian;

        return $this;
    }

    public function getImage()
    {
        return $this->image;
    }

    public function setImage($image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getPlantId(): ?Plant
    {
        return $this->plantId;
    }

    public function setPlantId(?Plant $plantId): self
    {
        $this->plantId = $plantId;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getLongitude(): ?string
    {
        return $this->longitude;
    }

    public function setLongitude(string $longitude): self
    {
        $this->longitude = $longitude;

        return $this;
    }

    public function getLatitude(): ?string
    {
        return $this->latitude;
    }

    public function setLatitude(string $latitude): self
    {
        $this->latitude = $latitude;

        return $this;
    }
}

MSPR/src/Controller/PostController.php
<?php

namespace App\Controller;

use App\Entity\Plant;
use App\Entity\Post;
use App\Entity\User;
use App\Form\PostFormType;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PostController extends AbstractController
{
    #[Route('/posts/{id}', name: 'app_post_detail')]
    public function detail(Post $post,Request $request,EntityManagerInterface $em, UserRepository $ur): Response
    {
        return $this->render('post/detail.html.twig', [
            'post' => $post,
            'users' => $ur->findAll()
        ]);
    }
    #[Route('/newpost', name: 'app_new_post')]
    public function addPost(Request $request,ManagerRegistry $doctrine): Response
    {
        $user = $this->getUser();
        $post = new Post();
        $form = $this->createForm(PostFormType::class, $post);
        $form->handleRequest($request);
        if($user != null && $form->isSubmitted() && $form->isValid()){
            $uploadFile = $form['image']->getData();;
            $originalFileName = pathinfo($uploadFile->getClientOriginalName(),PATHINFO_FILENAME);
            $safeFileName = preg_replace('/[^a-zA-Z0-9]/','_',$originalFileName);
            $newFileName = $safeFileName . '-'. uniqid() . '.' . $uploadFile->guessExtension();
            $uploadFile->move($this->getParameter('images_directory'),$newFileName);
            if($_POST['latitude'] && $_POST['longitude']){
                $post->setLongitude($_POST['longitude']);
                $post->setLatitude($_POST['latitude']);
            }
            $post->setImage($newFileName);
            $post->setUser($user);
            $em = $doctrine->getManager();
            $em->persist($post);
            $em->flush();

            $this->addFlash('message', 'post créé avec succès');
            return $this->redirectToRoute('app_main');
        }

        return $this->render('post/form.html.twig',[
            'postForm' => $form->createView(),]);


    }
}

MSPR/templates/post/detail.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('assets/css/detail.css') }}">
{% endblock %}
{% block body %}
    <div class="detail-card">
    <h2 class="detail-title">{{ post.title|capitalize }}</h2>
    <div class="container-detail">
        {% if app.user.id == post.user.id %}
            <div class="guard">
            <label for="guardian">Gardien :</label>
            {% if not post.guardian %}
                <div class="search_user">
                    <input id="input_search"  type="text" value="">
                    <div class="results">
                        {% for user in users %}
                            <span class="option" onclick="setGuardian(this)">{{user.email}}</span>
                        {% endfor %}
                    </div>
                </div>
            {% else %}
                <h4>
                    {{ post.guardian.email }}
                </h4>
            {% endif %}
        {% else %}
            {% if post.guardian is not empty %}
                <label for="guardian">Gardé par {{ post.guardian.email }}</label>
            {% endif %}
        {% endif %}
        <span id="res_fetch_guardian"></span>
            </div>
        {% set imagePath = '/uploads/images/' ~ post.image %}
        <p>{{ post.description }}</p>
        <div class="image">
            <img src="{{ imagePath }}" alt="" id="img_card">
        </div>
    </div>
    </div>
    <section>
        <h3>Espace commentaire</h3>
        <textarea id="comment" name="comment"
                  rows="5" cols="33">
        </textarea>
        <button id="btn-comment">Envoyer</button>
        <div id="comments-container">
            {% set i = 0 %}
            {% for comment in post.comments %}

            <div class="comment-card post_{{ i }}">
                <span class="delete_com id_{{ comment.id }} post_comment_{{ i }}"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="fill: rgba(0, 0, 0, 1);transform: ;msFilter:;"><path d="M21 5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V5zm-4.793 9.793-1.414 1.414L12 13.414l-2.793 2.793-1.414-1.414L10.586 12 7.793 9.207l1.414-1.414L12 10.586l2.793-2.793 1.414 1.414L13.414 12l2.793 2.793z"></path></svg></span>
                <div class="author" id="card_author">{{ comment.userComment.email }}
                    <span class="dateSend" id="card_date">{{ comment.sendDate|date }}</span>
                </div>
                <br>
                <div class="comment-content" id="card_content">{{ comment.content }}</div>
            </div>
                {% set i = i + 1 %}
                {% endfor %}
        </div>
    </section>
    <template id="comment-area">
        <div class="comment-card">
            <div class="author" id="card_author"><span class="dateSend" id="card_date"></span></div>
            <span class="delete_com"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="fill: rgba(0, 0, 0, 1);transform: ;msFilter:;"><path d="M21 5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V5zm-4.793 9.793-1.414 1.414L12 13.414l-2.793 2.793-1.414-1.414L10.586 12 7.793 9.207l1.414-1.414L12 10.586l2.793-2.793 1.414 1.414L13.414 12l2.793 2.793z"></path></svg></span>
            <br>
            <div class="comment-content" id="card_content"></div>
        </div>
    </template>
    <script>
        const btnComment = document.querySelector('#btn-comment');
        const deleteCom = document.querySelectorAll('.delete_com')

        updateComsArea()
        function updateComsArea(){
            deleteCom.forEach(element => {
                element.addEventListener('click', (e) => {
                    const idCom = e.currentTarget.classList[1].split('_')[1]
                    e.currentTarget.parentElement.remove()
                    deleteComment(idCom);
                })
            })
        }
        btnComment.addEventListener('click', () => {
            sendComment();
        });
        function deleteComment(id){
            const opts = {
                method: "POST",
                body: JSON.stringify({
                        post: {{ post.id }},
                        comment_id: id
                    }
                )};
            fetch('/api/deleteCommentByPost',opts)
                .then((res) => res.json())
                .then((res) => console.log(res))
        }
        function setGuardian(inpt) {
            const opts = {
                method: "POST",
                body: JSON.stringify({
                    post: {{ post.id }},
                    guardian: inpt.textContent
                }),

            };

            fetch('/api/guardian', opts)
                .then((res) => res.json())
                .then((res) => {
                    const txt = document.querySelector('#res_fetch_guardian');
                    if (res) {
                        txt.textContent = "Success !"
                        txt.classList.add('success')
                        txt.classList.remove('error')
                        inpt.disabled = true
                    } else {
                        txt.textContent = "Unknown user"
                        txt.classList.add('error')
                        txt.classList.remove('success')
                    }

                });
        }

        function sendComment() {
            const contentComment = document.querySelector('#comment').value
            const opts = {
                method: "POST",
                body: JSON.stringify({
                    post: {{ post.id }},
                    sender: {{ app.user.id }},
                    content: contentComment
                })
            };
            fetch('/api/addComment', opts)
                .then(res => res.json())
                .then(res => {
                    buildCommentPart()
                    document.querySelector('#comment').value = ""
                })
        }

        function fetchComments() {
            const opts = {
                method: "POST",
                body: JSON.stringify({
                    post: {{ post.id }},
                })
            };
        }
        function buildCommentPart() {
            const template = document.querySelector('#comment-area')
            const clone = template.content.cloneNode(true);
            const contentComment = document.querySelector('#comment').value
            const box = clone.querySelector('.comment-card');
            const author = clone.querySelector('#card_author');
            const date = clone.querySelector('#card_date');
            const content = clone.querySelector('#card_content')
            box.classList.add('new-box')
            author.textContent += "{{ app.user.email }}";
            date.textContent += new Date().toLocaleString();
            content.textContent = contentComment;
            box.classList.add('post_'+ {{ i }})
            document.querySelector('#comments-container').appendChild(clone);
        }
        const input = document.querySelector('#input_search')

        /**
         * add event listener on the input search to sort the select items with query
         */
        let elmts = ['click', 'keyup']

        elmts.forEach( evt =>
            input.addEventListener(evt, ()=> {
                const value = input.value.toUpperCase();
                const opt = document.querySelectorAll('.option')
                if(value.length >= 3){
                    for( i = 0; i < opt.length; i++){
                        let txtValue = opt[i].textContent || opt[i].innerText;
                        document.querySelector('.results').classList.add('active')
                        if (txtValue.toUpperCase().indexOf(value)> -1){
                            opt[i].style.display = "";
                        }else{
                            opt[i].style.display = "none"
                        }
                    }
                }

            })
        )
    </script>

{% endblock %}

MSPR/templates/post/form.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <link rel="stylesheet" href="{{ asset('assets/css/postForm.css') }}">
    <div id="card">
        {{ form_start(postForm) }}

        {{ form_row(postForm.title,{ 'label': 'Titre : '}) }}
        <br>
{#        {{ form_row(postForm.description,{ 'label': 'Description : '}) }}#}
        {{ form_label(postForm.description, 'Description : ') }}
        <input type="text" name="latitude" hidden>
        <input type="text" name="longitude" hidden>
        {{ form_widget(postForm.description, {'attr': {'class': 'form-control', 'rows': '5'}}) }}
        {{ form_errors(postForm.description) }}
        <br>
        {{ form_row(postForm.plantId,{ 'label': 'Plante : '}) }}
        <br>
        {{ form_row(postForm.image,{ 'label': 'Photo : '}) }}
        <br>
        <div class = "validateButton">
        {{ form_row(postForm.valider) }}
        </div>

        {{ form_end(postForm) }}
        {#  <form action="{{ path('app_new_post') }}" method="post" enctype="multipart/form-data">
            <label for="title">Titre : </label>
            <input type="text" name="title" id="title">
            <br>
            <label for="description">Description : </label>
            <textarea type="text" name="description" id="description"> </textarea>
            <br>
            <label for="plant">Plante : </label>
            <input type="text" name="plant" id="plant">
            <br>

            <label for="image">Photo : </label>
            <input type="file" name="img" id="image" accept=".jpg,.jpeg,.png">
            <br>
            {#<input type="text" placeholder="Plante" id="input_search">
        <div class="results">
            {% for plant in plants %}
                <a class="option">{{plant.label}}</a>
            {% endfor %}
        </div>
            <button type="submit">Envoyer</button>
        </form>#}
    </div>
    <script>
        window.navigator.geolocation.getCurrentPosition(function (position) {
            document.querySelector('input[name="latitude"]').value = position.coords.latitude;
            document.querySelector('input[name="longitude"]').value = position.coords.longitude;
        });
    </script>
{% endblock %}
{% block js %}

{% endblock %}